"""`policy init --from-scan`: reads a scan artifact, writes capability declarations.

Requires the `interbolt[wizard]` extra (`ruamel.yaml`), needed to edit an
existing policy file while preserving its comments and key order. This module
is only imported from inside `commands_policy.py`'s `--from-scan` branch, so
`interbolt policy init` and every other command work with no wizard extra
installed.
"""

from __future__ import annotations

import argparse
import importlib.resources
import os
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from pydantic import ValidationError
from rich.console import Console
from rich.markup import escape

from interbolt import Capability, ScanArtifact, ScanTool, UndetectedKind
from interbolt.cli.exit_codes import EXIT_OK, EXIT_USAGE
from interbolt.cli.render import emit_json
from interbolt.constants import ENV_API_KEY
from interbolt.errors import InterboltConfigError

try:
    from ruamel.yaml import YAML
except ImportError as exc:
    raise InterboltConfigError(
        "policy init --from-scan requires the ruamel.yaml package; install it "
        'with `pip install "interbolt[wizard]"`'
    ) from exc

_REVIEW_COMMENT = "review: generated by `interbolt policy init --from-scan`"
_TODO_COMMENT = "TODO: declare capabilities"

_GROUNDABLE_KINDS = (
    UndetectedKind.UNRESOLVED_IMPLEMENTATION,
    UndetectedKind.UNRESOLVED_TOOL_LIST,
)

# Each template is wrapped in a `sinks:` key matching its final nesting depth
# in the target document. ruamel anchors a block sequence's item comments to
# an absolute column recorded at parse time, which does not reflow if the
# parsed node is later moved to a different nesting depth; parsing at the
# depth the node will actually live at keeps those columns correct.
_REACHES_EXTERNAL_BLOCK = """\
sinks:
  {name}:
    capabilities: [reaches_external]
    rules:
      # {review}
      # Blocks this tool when any argument carries untrusted provenance.
      - name: block_untrusted_exfil
        when: taint.exists(t, t.trust == "untrusted")
        action: block
      # Gates the tool when all three lethal-trifecta legs are present in this
      # run, whether or not this call's own arguments carry a label. Survives a
      # model-mediated handoff that launders value-level taint.
      - name: gate_full_trifecta
        when: size(run.trifecta) >= 3
        action: require_approval
"""

_READS_PRIVATE_BLOCK = """\
sinks:
  {name}:
    capabilities: [reads_private]
    rules:
      # {review}
      # Gates the tool when all three lethal-trifecta legs are present in this
      # run, whether or not this call's own arguments carry a label. Survives a
      # model-mediated handoff that launders value-level taint.
      - name: gate_full_trifecta
        when: size(run.trifecta) >= 3
        action: require_approval
"""

_NEITHER_BLOCK = """\
sinks:
  {name}:
    capabilities: []
"""

_TODO_BLOCK = """\
sinks:
  {name}:
    capabilities: []  # {todo}
"""

_WrittenEntry = tuple[str, tuple[Capability, ...], int]


def run_from_scan(args: argparse.Namespace, console: Console) -> int:
    """Read a scan artifact and write capability declarations into a policy file.

    Walks every tool the artifact reports as undeclared, in interactive mode
    asking which capability applies to each and in `--non-interactive` mode
    writing a TODO placeholder for all of them, then writes the result back
    with comments and key order preserved.

    Args:
        args: Parsed CLI arguments for `policy init`, including `from_scan`
            and `non_interactive`.
        console: The console for this invocation.

    Returns:
        The process exit code; see `interbolt.cli.exit_codes`.
    """
    if os.environ.get(ENV_API_KEY):
        return _fail(
            console,
            args,
            f"policy init --from-scan is not accepted while {ENV_API_KEY} is "
            "set; the remote policy is authoritative. Use "
            "`interbolt policy propose` instead.",
        )

    try:
        artifact = ScanArtifact.model_validate_json(
            Path(args.from_scan).read_text(encoding="utf-8")
        )
    except (OSError, ValidationError) as exc:
        return _fail(
            console, args, f"could not read scan artifact {args.from_scan!r}: {exc}"
        )

    policy_path = Path(args.policy_path)
    yaml = _build_yaml()
    try:
        source_text = (
            policy_path.read_text(encoding="utf-8")
            if policy_path.exists()
            else importlib.resources.files("interbolt")
            .joinpath("policy.example.yaml")
            .read_text(encoding="utf-8")
        )
        document = yaml.load(source_text)
    except OSError as exc:
        return _fail(console, args, f"could not read {args.policy_path!r}: {exc}")
    except Exception as exc:  # noqa: BLE001 - ruamel's own YAMLError hierarchy
        return _fail(console, args, f"could not parse {args.policy_path!r}: {exc}")

    sinks_map = _ensure_sinks_map(yaml, document)
    undeclared = [tool for tool in artifact.tools if not tool.declared]
    written: list[_WrittenEntry] = []

    if args.non_interactive:
        for tool in undeclared:
            rule_count = _write_sink(
                yaml, sinks_map, tool.qualified_name, (), todo=True
            )
            written.append((tool.qualified_name, (), rule_count))
    else:
        for tool in undeclared:
            console.print()
            _print_tool_context(console, tool)
            capabilities = _prompt_capabilities(console, tool)
            if capabilities is None:
                continue
            rule_count = _write_sink(
                yaml, sinks_map, tool.qualified_name, capabilities, todo=False
            )
            written.append((tool.qualified_name, capabilities, rule_count))
        _offer_grounding(console, artifact, sinks_map)

    try:
        with policy_path.open("w", encoding="utf-8") as handle:
            yaml.dump(document, handle)
    except OSError as exc:
        return _fail(console, args, f"could not write {args.policy_path!r}: {exc}")

    _print_summary(console, args, policy_path, written)
    return EXIT_OK


def _fail(console: Console, args: argparse.Namespace, message: str) -> int:
    if args.format == "json":
        emit_json(console, {"command": "policy init", "error": message})
    else:
        console.print(f"[red]✗[/red] {escape(message)}")
    return EXIT_USAGE


def _build_yaml() -> YAML:
    """A round-tripping loader/dumper matching the packaged starter's indent style."""
    yaml = YAML()
    yaml.indent(mapping=2, sequence=4, offset=2)
    yaml.preserve_quotes = True
    yaml.width = 4096
    return yaml


def _ensure_sinks_map(yaml: YAML, document: Any) -> Any:  # noqa: ANN401 - ruamel CommentedMap
    if document.get("sinks") is None:
        document["sinks"] = yaml.load("sinks: {}\n")["sinks"]
    return document["sinks"]


def _capabilities_literal(capabilities: tuple[Capability, ...]) -> str:
    return "[" + ", ".join(c.value for c in capabilities) + "]"


def _write_sink(
    yaml: YAML,
    sinks_map: Any,  # noqa: ANN401 - ruamel CommentedMap
    name: str,
    capabilities: tuple[Capability, ...],
    *,
    todo: bool,
) -> int:
    """Write a new sink entry, or add only `capabilities:` to an existing one.

    A key already present in `sinks_map`, whether a bare null from an earlier
    grounding pass or a hand-written entry with its own rules, is never
    replaced: only its `capabilities` field is set, and any `rules:` it
    already carries is left untouched. Generated rules are written only when
    the entry is being created for the first time.

    Returns:
        The number of rules written for this entry.
    """
    if name in sinks_map:
        parsed = yaml.load(f"capabilities: {_capabilities_literal(capabilities)}\n")
        existing = sinks_map[name]
        if existing is None:
            sinks_map[name] = parsed
        else:
            existing["capabilities"] = parsed["capabilities"]
        return 0

    if todo:
        text = _TODO_BLOCK.format(name=name, todo=_TODO_COMMENT)
        rule_count = 0
    elif Capability.REACHES_EXTERNAL in capabilities:
        text = _REACHES_EXTERNAL_BLOCK.format(name=name, review=_REVIEW_COMMENT)
        rule_count = 2
    elif Capability.READS_PRIVATE in capabilities:
        text = _READS_PRIVATE_BLOCK.format(name=name, review=_REVIEW_COMMENT)
        rule_count = 1
    else:
        text = _NEITHER_BLOCK.format(name=name)
        rule_count = 0

    parsed_block = yaml.load(text)
    sinks_map[name] = parsed_block["sinks"][name]
    return rule_count


def _print_tool_context(console: Console, tool: ScanTool) -> None:
    console.print(f"[bold]{escape(tool.qualified_name)}[/bold]")
    if tool.collision:
        console.print("  more than one definition resolves to this name")
        console.print('  name one of them explicitly with @guard(tool="ns.name")')
        return
    if tool.definition is not None:
        console.print(
            f"  defined at {escape(tool.definition.path)}:{tool.definition.line}"
        )
    if tool.signature is not None:
        console.print(f"  signature: {escape(tool.signature)}")
    if tool.evidence:
        for item in tool.evidence:
            console.print(
                f"  touches {escape(item.symbol)} at {escape(item.path)}:{item.line}"
            )
    else:
        console.print("  no evidence recorded")


def _prompt_capabilities(
    console: Console, tool: ScanTool
) -> tuple[Capability, ...] | None:
    """Ask which capability applies to one tool. `None` means skip it.

    A closed stdin (piped input running dry, or an interactive Ctrl-D) also
    skips, rather than raising past this prompt: the tool stays undeclared
    and the next tool is offered a fresh prompt.
    """
    while True:
        try:
            answer = (
                console.input(
                    "  capabilities? [r]eads_private / [x]reaches_external / "
                    "[n]either / [s]kip: ",
                    markup=False,
                )
                .strip()
                .lower()
            )
        except EOFError:
            return None
        if answer in ("r", "reads_private"):
            return (Capability.READS_PRIVATE,)
        if answer in ("x", "reaches_external"):
            return (Capability.REACHES_EXTERNAL,)
        if answer in ("n", "neither"):
            return ()
        if answer in ("s", "skip", ""):
            return None
        console.print("  [yellow]![/yellow] enter r, x, n, or s")


def _offer_grounding(
    console: Console,
    artifact: ScanArtifact,
    sinks_map: Any,  # noqa: ANN401 - ruamel CommentedMap
) -> None:
    candidates = [
        item for item in artifact.undetected if item.kind in _GROUNDABLE_KINDS
    ]
    if not candidates:
        return
    console.print()
    plural = "" if len(candidates) == 1 else "s"
    console.print(
        f"{len(candidates)} unreadable surface{plural} could resolve from a policy name"
    )
    try:
        answer = console.input(
            "  comma-separated tool names to add as bare sink entries (blank to skip): "
        ).strip()
    except EOFError:
        return
    if not answer:
        return
    for name in (part.strip() for part in answer.split(",")):
        if name and name not in sinks_map:
            sinks_map[name] = None


def _capability_label(capabilities: tuple[Capability, ...]) -> str:
    return (
        ", ".join(c.value for c in capabilities) if capabilities else "no capabilities"
    )


def _print_summary(
    console: Console,
    args: argparse.Namespace,
    policy_path: Path,
    written: Sequence[_WrittenEntry],
) -> None:
    if args.format == "json":
        emit_json(
            console,
            {
                "command": "policy init",
                "policy_path": str(policy_path),
                "from_scan": args.from_scan,
                "written": [
                    {
                        "qualified_name": name,
                        "capabilities": [c.value for c in capabilities],
                        "rules": rule_count,
                    }
                    for name, capabilities, rule_count in written
                ],
            },
        )
        return

    noun = "entry" if len(written) == 1 else "entries"
    if not args.quiet:
        console.print(
            f"[green]✓[/green] wrote {len(written)} sink {noun} to "
            f"{escape(str(policy_path))}"
        )
    if not written:
        return

    console.print()
    name_width = max(len(name) for name, _, _ in written)
    label_width = max(len(_capability_label(caps)) for _, caps, _ in written)
    for name, capabilities, rule_count in written:
        label = _capability_label(capabilities)
        rule_word = "rule" if rule_count == 1 else "rules"
        console.print(
            f"  {escape(name).ljust(name_width)}    {label.ljust(label_width)}    "
            f"{rule_count} {rule_word}"
        )

    console.print()
    console.print(
        "Generated rules gate on provenance only. Review them before enabling\n"
        "enforcement, and add argument-level rules by hand where a tool needs them:\n"
        "https://docs.deconvolutelabs.com/docs/concepts/policies"
    )
    console.print()
    console.print(
        "Run with mode: dry_run first to see what this policy would have done."
    )
